# Generated by Django 4.1.7 on 2023-02-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_menu_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.FloatField(null=True, verbose_name='price'),
        ),
    ]
