# Generated by Django 4.1.7 on 2023-03-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_category_category_name_alter_menu_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe_address', models.CharField(max_length=255, unique=True, verbose_name='address')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_name', models.CharField(max_length=255)),
                ('social_media_link', models.URLField()),
            ],
            options={
                'unique_together': {('social_media_name', 'social_media_link')},
            },
        ),
    ]
