# Generated by Django 4.2.2 on 2023-06-11 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ordering.cart'),
        ),
    ]
